server:
  port: 8003
spring:
  application:
    name: NOTIFICATION-SERVICE
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate, dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/notification-service
    username: postgres
    password: 123456


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'