spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
